/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError } from './base';

/**
 * Base parameters for neural network
 * @export
 * @interface BaseParams
 */
export interface BaseParams {
    /**
     * 
     * @type {any}
     * @memberof BaseParams
     */
    'learning_rate': any;
    /**
     * 
     * @type {any}
     * @memberof BaseParams
     */
    'batch_size': any;
    /**
     * 
     * @type {any}
     * @memberof BaseParams
     */
    'input_length': any;
    /**
     * 
     * @type {any}
     * @memberof BaseParams
     */
    'epochs': any;
    /**
     * 
     * @type {any}
     * @memberof BaseParams
     */
    'validation_split': any;
}
/**
 * An enumeration.
 * @export
 * @interface BaselinePDMethod
 */
export interface BaselinePDMethod {
}
/**
 * Process model detailed view schema
 * @export
 * @interface BaselineProcessModelDetailedView
 */
export interface BaselineProcessModelDetailedView {
    /**
     * 
     * @type {any}
     * @memberof BaselineProcessModelDetailedView
     */
    'id': any;
    /**
     * 
     * @type {BaselinePDMethod}
     * @memberof BaselineProcessModelDetailedView
     */
    'algorithm': BaselinePDMethod;
    /**
     * 
     * @type {SchemaRef}
     * @memberof BaselineProcessModelDetailedView
     */
    'dataset': SchemaRef;
    /**
     * 
     * @type {ProcessModelMetricsView}
     * @memberof BaselineProcessModelDetailedView
     */
    'metrics': ProcessModelMetricsView;
}


/**
 * Process model list view schema
 * @export
 * @interface BaselineProcessModelListView
 */
export interface BaselineProcessModelListView {
    /**
     * 
     * @type {any}
     * @memberof BaselineProcessModelListView
     */
    'id': any;
    /**
     * 
     * @type {BaselinePDMethod}
     * @memberof BaselineProcessModelListView
     */
    'algorithm': BaselinePDMethod;
    /**
     * 
     * @type {SchemaRef}
     * @memberof BaselineProcessModelListView
     */
    'dataset': SchemaRef;
}


/**
 * Categorical feature metric schema
 * @export
 * @interface CategoricalMetric
 */
export interface CategoricalMetric {
    /**
     * 
     * @type {any}
     * @memberof CategoricalMetric
     */
    'name': any;
    /**
     * 
     * @type {any}
     * @memberof CategoricalMetric
     */
    'type'?: any;
    /**
     * 
     * @type {any}
     * @memberof CategoricalMetric
     */
    'unique_values': any;
    /**
     * 
     * @type {any}
     * @memberof CategoricalMetric
     */
    'value_counts': any;
}
/**
 * Dataset list view schema
 * @export
 * @interface DatasetDetailedView
 */
export interface DatasetDetailedView {
    /**
     * 
     * @type {any}
     * @memberof DatasetDetailedView
     */
    'id': any;
    /**
     * 
     * @type {any}
     * @memberof DatasetDetailedView
     */
    'name': any;
    /**
     * 
     * @type {any}
     * @memberof DatasetDetailedView
     */
    'description': any;
    /**
     * 
     * @type {any}
     * @memberof DatasetDetailedView
     */
    'size': any;
    /**
     * 
     * @type {DatasetMetrics}
     * @memberof DatasetDetailedView
     */
    'metrics': DatasetMetrics;
}
/**
 * Dataset list view schema
 * @export
 * @interface DatasetListView
 */
export interface DatasetListView {
    /**
     * 
     * @type {any}
     * @memberof DatasetListView
     */
    'id': any;
    /**
     * 
     * @type {any}
     * @memberof DatasetListView
     */
    'name': any;
    /**
     * 
     * @type {any}
     * @memberof DatasetListView
     */
    'description': any;
    /**
     * 
     * @type {any}
     * @memberof DatasetListView
     */
    'size': any;
}
/**
 * Dataset metrics schema
 * @export
 * @interface DatasetMetrics
 */
export interface DatasetMetrics {
    /**
     * 
     * @type {any}
     * @memberof DatasetMetrics
     */
    'values': any;
}
/**
 * Numerical feature metric schema
 * @export
 * @interface DatetimeMetric
 */
export interface DatetimeMetric {
    /**
     * 
     * @type {any}
     * @memberof DatetimeMetric
     */
    'name': any;
    /**
     * 
     * @type {any}
     * @memberof DatetimeMetric
     */
    'type'?: any;
    /**
     * 
     * @type {any}
     * @memberof DatetimeMetric
     */
    'mean': any;
    /**
     * 
     * @type {any}
     * @memberof DatetimeMetric
     */
    'median': any;
    /**
     * 
     * @type {any}
     * @memberof DatetimeMetric
     */
    'std': any;
    /**
     * 
     * @type {any}
     * @memberof DatetimeMetric
     */
    'min': any;
    /**
     * 
     * @type {any}
     * @memberof DatetimeMetric
     */
    'max': any;
    /**
     * 
     * @type {any}
     * @memberof DatetimeMetric
     */
    'q1': any;
    /**
     * 
     * @type {any}
     * @memberof DatetimeMetric
     */
    'q3': any;
}
/**
 * 
 * @export
 * @interface HTTPValidationError
 */
export interface HTTPValidationError {
    /**
     * 
     * @type {any}
     * @memberof HTTPValidationError
     */
    'detail'?: any;
}
/**
 * Base parameters for neural network
 * @export
 * @interface InceptionParams
 */
export interface InceptionParams {
    /**
     * 
     * @type {any}
     * @memberof InceptionParams
     */
    'learning_rate': any;
    /**
     * 
     * @type {any}
     * @memberof InceptionParams
     */
    'batch_size': any;
    /**
     * 
     * @type {any}
     * @memberof InceptionParams
     */
    'input_length': any;
    /**
     * 
     * @type {any}
     * @memberof InceptionParams
     */
    'epochs': any;
    /**
     * 
     * @type {any}
     * @memberof InceptionParams
     */
    'validation_split': any;
    /**
     * 
     * @type {any}
     * @memberof InceptionParams
     */
    'n_modules': any;
    /**
     * 
     * @type {any}
     * @memberof InceptionParams
     */
    'embedding_size': any;
}
/**
 * Process model detailed view schema
 * @export
 * @interface LearnedProcessModelView
 */
export interface LearnedProcessModelView {
    /**
     * 
     * @type {ProcessModelMetricsView}
     * @memberof LearnedProcessModelView
     */
    'metrics': ProcessModelMetricsView;
}
/**
 * An enumeration.
 * @export
 * @interface NeuralNetworkArchitecture
 */
export interface NeuralNetworkArchitecture {
}
/**
 * Numerical feature metric schema
 * @export
 * @interface NumericalMetric
 */
export interface NumericalMetric {
    /**
     * 
     * @type {any}
     * @memberof NumericalMetric
     */
    'name': any;
    /**
     * 
     * @type {any}
     * @memberof NumericalMetric
     */
    'type'?: any;
    /**
     * 
     * @type {any}
     * @memberof NumericalMetric
     */
    'mean': any;
    /**
     * 
     * @type {any}
     * @memberof NumericalMetric
     */
    'median': any;
    /**
     * 
     * @type {any}
     * @memberof NumericalMetric
     */
    'std': any;
    /**
     * 
     * @type {any}
     * @memberof NumericalMetric
     */
    'min': any;
    /**
     * 
     * @type {any}
     * @memberof NumericalMetric
     */
    'max': any;
    /**
     * 
     * @type {any}
     * @memberof NumericalMetric
     */
    'q1': any;
    /**
     * 
     * @type {any}
     * @memberof NumericalMetric
     */
    'q3': any;
}
/**
 * Process model metrics view schema
 * @export
 * @interface ProcessModelMetricsView
 */
export interface ProcessModelMetricsView {
    /**
     * 
     * @type {any}
     * @memberof ProcessModelMetricsView
     */
    'id': any;
    /**
     * 
     * @type {any}
     * @memberof ProcessModelMetricsView
     */
    'fitness': any;
    /**
     * 
     * @type {any}
     * @memberof ProcessModelMetricsView
     */
    'simplicity': any;
    /**
     * 
     * @type {any}
     * @memberof ProcessModelMetricsView
     */
    'precision': any;
    /**
     * 
     * @type {any}
     * @memberof ProcessModelMetricsView
     */
    'generalization': any;
}
/**
 * Schema reference for mongoengine
 * @export
 * @interface SchemaRef
 */
export interface SchemaRef {
    /**
     * 
     * @type {any}
     * @memberof SchemaRef
     */
    'id': any;
}
/**
 * Status schema for API responses
 * @export
 * @interface StatusResponse
 */
export interface StatusResponse {
    /**
     * 
     * @type {any}
     * @memberof StatusResponse
     */
    'status': any;
    /**
     * 
     * @type {any}
     * @memberof StatusResponse
     */
    'id'?: any;
}
/**
 * Model parameters schema for neural network creation
 * @export
 * @interface TrainParameters
 */
export interface TrainParameters {
    /**
     * 
     * @type {any}
     * @memberof TrainParameters
     */
    'name': any;
    /**
     * 
     * @type {NeuralNetworkArchitecture}
     * @memberof TrainParameters
     */
    'architecture': NeuralNetworkArchitecture;
    /**
     * 
     * @type {any}
     * @memberof TrainParameters
     */
    'dataset_id': any;
    /**
     * 
     * @type {any}
     * @memberof TrainParameters
     */
    'parameters': any;
}


/**
 * Model parameters schema for neural network creation
 * @export
 * @interface TrainedModelDetailedView
 */
export interface TrainedModelDetailedView {
    /**
     * 
     * @type {any}
     * @memberof TrainedModelDetailedView
     */
    'id': any;
    /**
     * 
     * @type {SchemaRef}
     * @memberof TrainedModelDetailedView
     */
    'dataset': SchemaRef;
    /**
     * 
     * @type {any}
     * @memberof TrainedModelDetailedView
     */
    'parameters': any;
    /**
     * 
     * @type {NeuralNetworkArchitecture}
     * @memberof TrainedModelDetailedView
     */
    'architecture': NeuralNetworkArchitecture;
    /**
     * 
     * @type {any}
     * @memberof TrainedModelDetailedView
     */
    'created_at': any;
    /**
     * 
     * @type {any}
     * @memberof TrainedModelDetailedView
     */
    'edited_at': any;
}


/**
 * Model parameters schema for neural network creation
 * @export
 * @interface TrainedModelListView
 */
export interface TrainedModelListView {
    /**
     * 
     * @type {any}
     * @memberof TrainedModelListView
     */
    'id': any;
    /**
     * 
     * @type {NeuralNetworkArchitecture}
     * @memberof TrainedModelListView
     */
    'architecture': NeuralNetworkArchitecture;
    /**
     * 
     * @type {SchemaRef}
     * @memberof TrainedModelListView
     */
    'dataset': SchemaRef;
}


/**
 * 
 * @export
 * @interface ValidationError
 */
export interface ValidationError {
    /**
     * 
     * @type {any}
     * @memberof ValidationError
     */
    'loc': any;
    /**
     * 
     * @type {any}
     * @memberof ValidationError
     */
    'msg': any;
    /**
     * 
     * @type {any}
     * @memberof ValidationError
     */
    'type': any;
}

/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Create new dataset
         * @summary Create Dataset
         * @param {any} name 
         * @param {any} description 
         * @param {any} file 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createDatasetDatasetPost: async (name: any, description: any, file: any, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'name' is not null or undefined
            assertParamExists('createDatasetDatasetPost', 'name', name)
            // verify required parameter 'description' is not null or undefined
            assertParamExists('createDatasetDatasetPost', 'description', description)
            // verify required parameter 'file' is not null or undefined
            assertParamExists('createDatasetDatasetPost', 'file', file)
            const localVarPath = `/dataset`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();

            if (name !== undefined) {
                localVarQueryParameter['name'] = name;
            }

            if (description !== undefined) {
                localVarQueryParameter['description'] = description;
            }


            if (file !== undefined) { 
                localVarFormParams.append('file', new Blob([file], { type: "application/json", }));
            }
    
    
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Create a neural network to be trained
         * @summary Create Model
         * @param {TrainParameters} trainParameters 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createModelModelTrainPost: async (trainParameters: TrainParameters, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'trainParameters' is not null or undefined
            assertParamExists('createModelModelTrainPost', 'trainParameters', trainParameters)
            const localVarPath = `/model/train`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(trainParameters, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get trained neural network by id
         * @summary Get Baseline Petri Net
         * @param {any} processId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBaselinePetriNetBaselineProcessIdVisGet: async (processId: any, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'processId' is not null or undefined
            assertParamExists('getBaselinePetriNetBaselineProcessIdVisGet', 'processId', processId)
            const localVarPath = `/baseline/{process_id}/vis`
                .replace(`{${"process_id"}}`, encodeURIComponent(String(processId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get process model by id
         * @summary Get Baseline Process Model
         * @param {any} processId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBaselineProcessModelBaselineProcessIdGet: async (processId: any, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'processId' is not null or undefined
            assertParamExists('getBaselineProcessModelBaselineProcessIdGet', 'processId', processId)
            const localVarPath = `/baseline/{process_id}`
                .replace(`{${"process_id"}}`, encodeURIComponent(String(processId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get list of baseline process models for dataset
         * @summary Get Baseline Processes
         * @param {any} datasetId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBaselineProcessesDatasetDatasetIdBaselinesGet: async (datasetId: any, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'datasetId' is not null or undefined
            assertParamExists('getBaselineProcessesDatasetDatasetIdBaselinesGet', 'datasetId', datasetId)
            const localVarPath = `/dataset/{dataset_id}/baselines/`
                .replace(`{${"dataset_id"}}`, encodeURIComponent(String(datasetId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get dataset by id
         * @summary Get Dataset
         * @param {any} datasetId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDatasetDatasetDatasetIdGet: async (datasetId: any, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'datasetId' is not null or undefined
            assertParamExists('getDatasetDatasetDatasetIdGet', 'datasetId', datasetId)
            const localVarPath = `/dataset/{dataset_id}`
                .replace(`{${"dataset_id"}}`, encodeURIComponent(String(datasetId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get list of datasets
         * @summary Get Datasets
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDatasetsDatasetGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/dataset`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get trained neural network by id
         * @summary Get Learned Petri Net
         * @param {any} modelId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLearnedPetriNetModelModelIdProcessVisGet: async (modelId: any, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'modelId' is not null or undefined
            assertParamExists('getLearnedPetriNetModelModelIdProcessVisGet', 'modelId', modelId)
            const localVarPath = `/model/{model_id}/process/vis`
                .replace(`{${"model_id"}}`, encodeURIComponent(String(modelId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get trained neural network by id
         * @summary Get Learned Process Model
         * @param {any} modelId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLearnedProcessModelModelModelIdProcessGet: async (modelId: any, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'modelId' is not null or undefined
            assertParamExists('getLearnedProcessModelModelModelIdProcessGet', 'modelId', modelId)
            const localVarPath = `/model/{model_id}/process/`
                .replace(`{${"model_id"}}`, encodeURIComponent(String(modelId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get trained neural network by id
         * @summary Get Trained Model
         * @param {any} modelId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTrainedModelModelModelIdGet: async (modelId: any, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'modelId' is not null or undefined
            assertParamExists('getTrainedModelModelModelIdGet', 'modelId', modelId)
            const localVarPath = `/model/{model_id}`
                .replace(`{${"model_id"}}`, encodeURIComponent(String(modelId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Get list of trained neural networks
         * @summary Get Trained Models
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTrainedModelsModelGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/model`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * Create new dataset
         * @summary Create Dataset
         * @param {any} name 
         * @param {any} description 
         * @param {any} file 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createDatasetDatasetPost(name: any, description: any, file: any, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<StatusResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createDatasetDatasetPost(name, description, file, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Create a neural network to be trained
         * @summary Create Model
         * @param {TrainParameters} trainParameters 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createModelModelTrainPost(trainParameters: TrainParameters, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<StatusResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createModelModelTrainPost(trainParameters, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Get trained neural network by id
         * @summary Get Baseline Petri Net
         * @param {any} processId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getBaselinePetriNetBaselineProcessIdVisGet(processId: any, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getBaselinePetriNetBaselineProcessIdVisGet(processId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Get process model by id
         * @summary Get Baseline Process Model
         * @param {any} processId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getBaselineProcessModelBaselineProcessIdGet(processId: any, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BaselineProcessModelDetailedView>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getBaselineProcessModelBaselineProcessIdGet(processId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Get list of baseline process models for dataset
         * @summary Get Baseline Processes
         * @param {any} datasetId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getBaselineProcessesDatasetDatasetIdBaselinesGet(datasetId: any, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getBaselineProcessesDatasetDatasetIdBaselinesGet(datasetId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Get dataset by id
         * @summary Get Dataset
         * @param {any} datasetId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDatasetDatasetDatasetIdGet(datasetId: any, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DatasetDetailedView>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getDatasetDatasetDatasetIdGet(datasetId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Get list of datasets
         * @summary Get Datasets
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDatasetsDatasetGet(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getDatasetsDatasetGet(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Get trained neural network by id
         * @summary Get Learned Petri Net
         * @param {any} modelId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getLearnedPetriNetModelModelIdProcessVisGet(modelId: any, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getLearnedPetriNetModelModelIdProcessVisGet(modelId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Get trained neural network by id
         * @summary Get Learned Process Model
         * @param {any} modelId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getLearnedProcessModelModelModelIdProcessGet(modelId: any, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LearnedProcessModelView>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getLearnedProcessModelModelModelIdProcessGet(modelId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Get trained neural network by id
         * @summary Get Trained Model
         * @param {any} modelId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTrainedModelModelModelIdGet(modelId: any, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TrainedModelDetailedView>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTrainedModelModelModelIdGet(modelId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Get list of trained neural networks
         * @summary Get Trained Models
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getTrainedModelsModelGet(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<any>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTrainedModelsModelGet(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * Create new dataset
         * @summary Create Dataset
         * @param {any} name 
         * @param {any} description 
         * @param {any} file 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createDatasetDatasetPost(name: any, description: any, file: any, options?: any): AxiosPromise<StatusResponse> {
            return localVarFp.createDatasetDatasetPost(name, description, file, options).then((request) => request(axios, basePath));
        },
        /**
         * Create a neural network to be trained
         * @summary Create Model
         * @param {TrainParameters} trainParameters 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createModelModelTrainPost(trainParameters: TrainParameters, options?: any): AxiosPromise<StatusResponse> {
            return localVarFp.createModelModelTrainPost(trainParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * Get trained neural network by id
         * @summary Get Baseline Petri Net
         * @param {any} processId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBaselinePetriNetBaselineProcessIdVisGet(processId: any, options?: any): AxiosPromise<any> {
            return localVarFp.getBaselinePetriNetBaselineProcessIdVisGet(processId, options).then((request) => request(axios, basePath));
        },
        /**
         * Get process model by id
         * @summary Get Baseline Process Model
         * @param {any} processId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBaselineProcessModelBaselineProcessIdGet(processId: any, options?: any): AxiosPromise<BaselineProcessModelDetailedView> {
            return localVarFp.getBaselineProcessModelBaselineProcessIdGet(processId, options).then((request) => request(axios, basePath));
        },
        /**
         * Get list of baseline process models for dataset
         * @summary Get Baseline Processes
         * @param {any} datasetId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBaselineProcessesDatasetDatasetIdBaselinesGet(datasetId: any, options?: any): AxiosPromise<any> {
            return localVarFp.getBaselineProcessesDatasetDatasetIdBaselinesGet(datasetId, options).then((request) => request(axios, basePath));
        },
        /**
         * Get dataset by id
         * @summary Get Dataset
         * @param {any} datasetId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDatasetDatasetDatasetIdGet(datasetId: any, options?: any): AxiosPromise<DatasetDetailedView> {
            return localVarFp.getDatasetDatasetDatasetIdGet(datasetId, options).then((request) => request(axios, basePath));
        },
        /**
         * Get list of datasets
         * @summary Get Datasets
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDatasetsDatasetGet(options?: any): AxiosPromise<any> {
            return localVarFp.getDatasetsDatasetGet(options).then((request) => request(axios, basePath));
        },
        /**
         * Get trained neural network by id
         * @summary Get Learned Petri Net
         * @param {any} modelId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLearnedPetriNetModelModelIdProcessVisGet(modelId: any, options?: any): AxiosPromise<any> {
            return localVarFp.getLearnedPetriNetModelModelIdProcessVisGet(modelId, options).then((request) => request(axios, basePath));
        },
        /**
         * Get trained neural network by id
         * @summary Get Learned Process Model
         * @param {any} modelId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLearnedProcessModelModelModelIdProcessGet(modelId: any, options?: any): AxiosPromise<LearnedProcessModelView> {
            return localVarFp.getLearnedProcessModelModelModelIdProcessGet(modelId, options).then((request) => request(axios, basePath));
        },
        /**
         * Get trained neural network by id
         * @summary Get Trained Model
         * @param {any} modelId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTrainedModelModelModelIdGet(modelId: any, options?: any): AxiosPromise<TrainedModelDetailedView> {
            return localVarFp.getTrainedModelModelModelIdGet(modelId, options).then((request) => request(axios, basePath));
        },
        /**
         * Get list of trained neural networks
         * @summary Get Trained Models
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getTrainedModelsModelGet(options?: any): AxiosPromise<any> {
            return localVarFp.getTrainedModelsModelGet(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
    /**
     * Create new dataset
     * @summary Create Dataset
     * @param {any} name 
     * @param {any} description 
     * @param {any} file 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public createDatasetDatasetPost(name: any, description: any, file: any, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).createDatasetDatasetPost(name, description, file, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Create a neural network to be trained
     * @summary Create Model
     * @param {TrainParameters} trainParameters 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public createModelModelTrainPost(trainParameters: TrainParameters, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).createModelModelTrainPost(trainParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get trained neural network by id
     * @summary Get Baseline Petri Net
     * @param {any} processId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getBaselinePetriNetBaselineProcessIdVisGet(processId: any, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getBaselinePetriNetBaselineProcessIdVisGet(processId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get process model by id
     * @summary Get Baseline Process Model
     * @param {any} processId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getBaselineProcessModelBaselineProcessIdGet(processId: any, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getBaselineProcessModelBaselineProcessIdGet(processId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get list of baseline process models for dataset
     * @summary Get Baseline Processes
     * @param {any} datasetId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getBaselineProcessesDatasetDatasetIdBaselinesGet(datasetId: any, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getBaselineProcessesDatasetDatasetIdBaselinesGet(datasetId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get dataset by id
     * @summary Get Dataset
     * @param {any} datasetId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getDatasetDatasetDatasetIdGet(datasetId: any, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getDatasetDatasetDatasetIdGet(datasetId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get list of datasets
     * @summary Get Datasets
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getDatasetsDatasetGet(options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getDatasetsDatasetGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get trained neural network by id
     * @summary Get Learned Petri Net
     * @param {any} modelId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getLearnedPetriNetModelModelIdProcessVisGet(modelId: any, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getLearnedPetriNetModelModelIdProcessVisGet(modelId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get trained neural network by id
     * @summary Get Learned Process Model
     * @param {any} modelId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getLearnedProcessModelModelModelIdProcessGet(modelId: any, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getLearnedProcessModelModelModelIdProcessGet(modelId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get trained neural network by id
     * @summary Get Trained Model
     * @param {any} modelId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getTrainedModelModelModelIdGet(modelId: any, options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getTrainedModelModelModelIdGet(modelId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get list of trained neural networks
     * @summary Get Trained Models
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DefaultApi
     */
    public getTrainedModelsModelGet(options?: AxiosRequestConfig) {
        return DefaultApiFp(this.configuration).getTrainedModelsModelGet(options).then((request) => request(this.axios, this.basePath));
    }
}


